title: CoreX | Premium Gym Apparel
description: >- # this means newlines are ignored until double space
  Never Settle for Average.
baseurl: "" # leave empty for custom domains
url: "https://www.corexwear.se"
theme: minima
permalink: pretty
